### ISSUE TITLE
Wiring plan available to connect this display to the D1 mini?

### ISSUE THREAD

**Issue by AWSW-de** [akasoggybunz/Wemos-Mini-D1-with-1.44-TFT-LCD-ST7735-Driver#1]
Hello,

first of all thanks for this helping video and the code. This seems exactly to solve my problem, because the kit came without any documentation.

Can you please post a wiring plan down which connector of the display has to connect to the one on the D1 mini?

Thanks a lot in advance.

Kind regards

**Comment by akasoggybunz** [comment]
@AWSW2017 I have added the wiring diagram that corresponds with the code. 
--------------------------------
Wemos Pins -> TFT Screen Pins
--------------------------------
D1 -> CS
D2 -> DC
D0 -> RES
D5 -> SCL
D7 -> SDA
3v3 -> VCC
G -> GND

**Comment by AWSW-de** [comment]
Hello akasoggybunz,
thanks a lot. I will try that next year. ;-)
Have a good start into 2019.
Kind regards

**Comment by akasoggybunz** [comment]
@AWSW2017 Happy new year! I am going to close this issue, just reopen it if you have any troubles.
